###
POST localhost:8081/v2/token/valid?right=ADD_RESERVATIONS
Content-Type: application/json
Token: ust:name-nickname-au-ru-login-ar-rr+xst:position-nn-create-delete-company-customer-cut+name:Root+rights:[USER, TRAINEE, ADD_USERS, REMOVE_USERS, ORDER_FOOD, ADD_RESERVATIONS, REMOVE_RESERVATIONS]

###
POST localhost:8082/vi/reservations
Content-Type: application/json
Token: ust:name-nickname-au-ru-login-ar-rr+xst:position-nn-create-delete-company-customer-cut+name:Root+rights:[USER, TRAINEE, ADD_USERS, REMOVE_USERS, ORDER_FOOD, ADD_RESERVATIONS, REMOVE_RESERVATIONS]

{
  "customerName" : "Customer",
  "startDate": "2022-01-10T15:23:44Z",
  "endDate": "2022-02-10T15:23:44Z",
  "petType": "CAT"
}