### GET token
GET http://localhost:8081/v1/authentication/test:test

### GET token local
GET http://localhost:8080/vi/auth/test:test

### GET check token
GET http://localhost:8081/v1/authentication/scope/dXNlck5hbWU9dGVzdDt2YWxpZFRpbWU9MjAyNC0wNi0yOFQxNjoxODowNi4wMTUwODgxMTZaO3Njb3BlPXVzZXItdGVzdC1zY29wZTtpZD01MzM0NjkxNi01NGQ0LTRjZTgtYTUzOS1iNjgxM2E0N2Y2ZjU

### POST check token
POST http://localhost:8080/vi/auth/dXNlck5hbWU9dGVzdDt2YWxpZFRpbWU9MjAyNC0wNi0yOFQxNjozNDo0NC4xMzM5MjIwNDhaO3Njb3BlPXVzZXItdGVzdC1zY29wZTtpZD01MzM0NjkxNi01NGQ0LTRjZTgtYTUzOS1iNjgxM2E0N2Y2ZjU